[[build.env]]
name = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
value = "pk_test_ZHJpdmluZy1zaGFkLTEzLmNsZXJrLmFjY291bnRzLmRldiQ"
name = "CLERK_SECRET_KEY"
value = "sk_test_LxBnc7ZklS1glEWdJds8vcMUizewfqLxeUSOCutjbq"
name = "NEXT_PUBLIC_CLERK_SIGN_IN_URL"
value = "/sign-in"
name = "NEXT_PUBLIC_CLERK_SIGN_UP_URL"
value = "/sign-up"
name = "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL"
value = "/"
name = "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL"
value = "/"
name = "OPENAI_API_KEY"
value = "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"
name = "REPLICATE_API_TOKEN"
value = "r8_bd7I03PYl65LYuhHlUPwuckv53QM1lH1rydSP"
name = "UPSTASH_REDIS_REST_URL"
value = "https://capital-halibut-38913.upstash.io"
name = "UPSTASH_REDIS_REST_TOKEN"
value = "AZgBASQgMjFkMjFmY2EtNjg2Zi00MDFlLWI0MGEtOWUzN2UzMjVlMzUxOWQ5YzAyMDg5NTMwNDQyY2FmZDFkZTAxYjM3ZTU3Yjk="
name = "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME"
value = "dw7vsz6ad"
name = "PINECONE_API_KEY"
value = "5210c51d-dfd2-4ec5-80ff-aca73e923f57"
name = "PINECONE_ENVIRONMENT"
value = "gcp-starter"
name = "PINECONE_INDEX"
value = "companian"
name = "DATABASE_URL"
value = "mysql://zykp1gm5iibszlw5ftoe:pscale_pw_h0NKH46rOAtK66EhEUsjyFIVIldY1LZ9r1iILhHRqYF@aws.connect.psdb.cloud/ai-saas?sslaccept=strict"
name = "STRIPE_API_KEY"
value = "sk_test_51NfOvqJxVNuPHewYVZje8djhMpjAVP1kyqZGRse8lDD5JtXvshfuSAFyQK5iBXDtIVaDBRyRfxmmcLxHnVf1uGbD001jnLq8hc"
name = "NEXT_PUBLIC_APP_URL"
value = "http://localhost:3000"
name = "STRIPE_WEBHOOK_SECRET"
value = "whsec_2d5c19c91bc580cb953663cf64be79274e9449561a3c1d450cd0dcc679ce0cf5"